algoritmo "Calcula_Média_10alunos"
// Função : Calcula a média das duas notas de cada aluno
// Autor : Gabriel Garcia da Silva
// Data : 20/09/2022

var

n1, n2, num_final: inteiro
media: real

inicio
repita
escreval("Digite a Primeira nota")
leia(n1)
escreval("Digite a Segunda nota")
leia(n2)
media<- (n1+n2)/2
escreval("A média é igual a: ", media)
num_final<- num_final+1
ate (num_final=10)

fimalgoritmo

