algoritmo "Número_inicial_final"
// Função : Exibe todos os números contidos entre os números digitados pelo usuário
// Autor : Gabriel Garcia da Silva
// Data : 06/09/2022

var
 contador, i, num1, num2, primo: inteiro
inicio
    escreva ("Digite um número inicial: ")
    leia(num1)
    escreva ("Digite um número final: ")
    leia (num2)
    para contador de num1 ate num2 faca

escreval (contador)
fimpara
fimalgoritmo
