algoritmo "exemplo_02"
// Função : Conta a quantidade de pessoas com idade maior ou igual a 18
// Autor : Gabriel Garcia da Silva
// Data : 20/09/2022

var

idade, qtde, contador: inteiro


inicio

para contador de 1 ate 10 faca
     escreval("Digite a idade: ")
     leia(idade)
     se idade>= 18 entao
        qtde <- qtde+1
     fimse
fimpara
escreval("No total de ",qtde," pessoas com idade maior ou igual a 18")

fimalgoritmo

