algoritmo "Competição_Vôlei"
// Função : Informa em que categoria de boxe o usuário está
// Autor : Gabriel Garcia
// Data : 02/08/2022


var
idade: inteiro
altura: real

inicio

escreval("Qual sua idade?")
leia(idade)
escreval("Qual sua altura?")
leia(altura)

 se (altura < 1.75)entao
     escreval("Você não pode participar")

 senao entao
     escreval("Você pode participar")

 fimse
fimalgoritmo
