algoritmo "Somar_frações"
// Função : Exibe todos os números primos de 1 à 500
// Autor : Gabriel Garcia da Silva
// Data : 06/09/2022

var
num_int, contador: inteiro
resultado: real
inicio
    escreva ("Digite um número inteiro: ")
    leia(num_int)

    para contador de 1 ate num_int faca
    
    resultado <- resultado + (1/contador)

    fimpara
    escreval ("O resultado é: ",resultado)
fimalgoritmo



