algoritmo "semnome"
// Função : Calcular a média de 2 notas
// Autor : Gabriel Garcia
// Data : 26/04/2022
// Seção de Declarações
var
p1,p2,media: real
inicio
// Dados de Entrada
escreval ("Entre com um valor para P1")
leia (p1)
escreval ("Entre com um valor para P2")
leia (p2)
// Fim dos Dados de Entrada
// Processamento
media <- (p1+p2)/2
// Fim_Processamento

// Dados de Saída
escreval ("A média do aluno é: ",media)
// FIm dos Dados de Saída

fimalgoritmo
